name: miranda
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - black
  - bump2version
  - cdsapi
  - cftime
  - clisops
  - custom-inherit >=2.3.0
  - dask
  - distributed
  - ecmwf-api-client
  - fabric
  - fiona
  - flake8
  - geojson
  - h5netcdf
  - intake
  - intake-esm
  - netCDF4
  - numcodecs
  - numpy
  - pandas
  - paramiko >=2.6.0
  - pint
  - pre-commit
  - pyproj
  - pytest
  - python >=3.7
  - pyupgrade
  - rasterio
  - regionmask
  - requests
  - rioxarray
  - s3fs
  - schema
  - scp
  - shapely
  - tox
  - wheel
  - xarray
  - xclim
  - zarr
  - pip
  - pip:
    - pyessv
