name: miranda
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.15
  - cdsapi
  - cftime >=1.4.1
  - cf-xarray >=0.10.4
  - clisops >=0.16.1
  - dask >=2024.8.1
  - distributed >=2.0
  - ecmwf-api-client
  - filelock >=3.14.0
  - h5netcdf >=1.5.0
  - h5py >=3.12.1
  - intake
  - intake-esm
  - numcodecs <0.16
  - numpy >=1.25
  - packaging >=24.0
  - pandas >=1.0.0
  - pyessv
  - pyproj
  - pyyaml >=6.0.1
  - regionmask >=0.13.0
  - requests >=2.31.0
  - s3fs
  - schema >=0.7.7
  - shapely >=2.0
  - xarray >=2023.11.0
  - xclim >=0.57.0
  - xesmf
  - zarr
  # Dev tools and testing
  - pip >=25.2
  - bump-my-version >=1.2.3
  - codespell >=2.4.1
  - coverage >=7.5.0
  - deptry >=0.23.0
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - mypy >=1.18.2
  - numpydoc >=1.9.0
  - pooch >=1.8.0
  - pre-commit >=3.5.0
  - pytest >=8.3.2
  - pytest-cov >=5.0.0
  - pytest-xdist >=3.2.0
  - ruff >=0.13.3
  - tox >=4.30.3
  - vulture >=2.14
  - watchdog >=4.0.0
  - yamllint >=1.35.1
